name: Deploy_Tutorial_NestJs # Nếu ko có 'name' thì mặc định hiển thị tên .github/workflows/develop.yml
on: 
  push:
    branches:
      - "develop"
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Build Example
        uses: actions/checkout@v3