name: Deploy tutorial-nestjs
on: 
  push:
    branches:
      - "develop"
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "USERNAME=KHANH_NB" >> $GITHUB_ENV
      - run: echo Hello, $USERNAME